### ISSUE TITLE
“(null)” in output

### ISSUE THREAD

**Issue by larrypl** [ColumPaget/ColumsCut#8]
I already mentioned this in another comment, but wanted to make it a separate issue, plus this is an interesting (to me) use of ccut - make a rocket ship, with a count-down
```
larryp-mbp:ColumsCut larry$ for ((i=1; i<=10; i++)); do for ((j=1; j<=i; j++)); do echo -n $j\ ; done; echo; done | ./ccut -d ' ' -f 8-1 | cat -v
(null)(null)(null)(null)(null)(null) 1
      2 1
     3 2 1
    4 3 2 1
   5 4 3 2 1
  6 5 4 3 2 1
 7 6 5 4 3 2 1
8 7 6 5 4 3 2 1
8 7 6 5 4 3 2 1
8 7 6 5 4 3 2 1
```
Should probably come out
```
       1
      2 1
     3 2 1
    4 3 2 1
   5 4 3 2 1
  6 5 4 3 2 1
 7 6 5 4 3 2 1
8 7 6 5 4 3 2 1
8 7 6 5 4 3 2 1
8 7 6 5 4 3 2 1
```

**Comment by ColumPaget** [comment]
Ah, yes, this is because ccut attempts to use the delimiter that it actually finds in the input, rather than the delimiter supplied on the command line. This is because you can supply multiple delimiters on the command line, and it wouldn't know which to pick.

I'll use the first command-line delimiter in the situation that the input delimiter is 'null'.

**Comment by ColumPaget** [comment]
Okay, this should be fixed now! I got a rocketship. ;-)

**Comment by larrypl** [comment]
Cool! Thanks!
